### ISSUE TITLE
考虑尝试把QQ.Framework的TargetFramework更改为netstandard

### ISSUE THREAD

**Issue by lhyqy5** [luojinfang/PCQQ-Protocol#10]
现在QQ.Framework在解决方案中有两个版本,如果能改成netstandard的,可以只保留一个,同时能够适配的平台也更多.
https://docs.microsoft.com/zh-cn/dotnet/standard/net-standard

**Comment by luojinfang** [comment]
一个很不错的建议

**Comment by luojinfang** [comment]
我把工程上了travis-ci，现在好像只有Mono会报错
