### ISSUE TITLE
怎么才能把开源项目那个引用链接到原本的库

### ISSUE THREAD

**Issue by luojinfang** [luojinfang/PCQQ-Protocol#13]
Iconic.Zlib.Netstandard想点击这个文件夹的时候跳转到https://github.com/HelloKitty/Iconic.Zlib.Netstandard

**Comment by WhileKing** [comment]
如果只是加的引用， 那么在git上是会跳转到原仓库的。
要不就直接把那个项目download下来， 然后移除git文件，当一个普通文件夹传上来。

**Comment by luojinfang** [comment]
明白了  我直接download下来提交上来了
