### ISSUE TITLE
还有好多待实现的功能，任重而道远。 

### ISSUE THREAD

**Issue by yruson** [luojinfang/PCQQ-Protocol#19]
感谢，还有好多待实现的功能，任重而道远。 
另外这个是基于什么研究的啊，感觉好高深的样子。那些0xXX的，以及消息包。如何知道对应去扩展写什么消息包呢？

SmartQQ是停止维护了所以接口不稳定了吗？

**Comment by luojinfang** [comment]
SmartQQ我没写过不太清楚，那个项目是fork别人的自己没有用过，这个是基于PCQQ的，还有一大堆东西没弄

**Comment by yruson** [comment]
这个是基于什么研究的啊，那些0xXX的，以及消息包。如何知道对应去扩展写什么消息包呢？
看能不能做点啥贡献 ^_^
