### ISSUE TITLE
接受图片和文字消息时只能获取到第一个图片或者文字

### ISSUE THREAD

**Issue by tw1997** [luojinfang/PCQQ-Protocol#35]
接受图片和文字的消息时（同时在一个消息中发送图文）

![f055406bddf311953c15a25da95843f7](https://user-images.githubusercontent.com/15799365/45300366-b8565480-b540-11e8-860f-6bb094036212.jpg)

![tim 20180910212903](https://user-images.githubusercontent.com/15799365/45300383-c73d0700-b540-11e8-85f5-b0bec3bd1de8.png)

只能获取到第一个图片或者文字。

**Comment by WhileKing** [comment]
目前协议还在解析中， 欢迎一起提供支持。

**Comment by WhileKing** [comment]
欢迎加群：26224272 共同讨论。
