### ISSUE TITLE
是否应移除MigrationBackup？

### ISSUE THREAD

**Issue by sgkoishi** [luojinfang/PCQQ-Protocol#46]
目前代码库中含有MigrationBackup文件夹，来自下列提交：
https://github.com/luojinfang/PCQQ-Protocol/commit/b74e3997eb84616ef7fab0d0bb54233c51a82d4d

这些文件是有意加入版本库的吗？

**Comment by luojinfang** [comment]
自动生成的，清道夫加油

**Comment by sgkoishi** [comment]
![告辞](https://ww3.sinaimg.cn/large/6af89bc8gw1f8oeiunyjcj203c036gle.jpg)
