### ISSUE TITLE
在公司网络下使用问题

### ISSUE THREAD

**Issue by wzfxue** [luojinfang/PCQQ-Protocol#67]
` public ReceiveData Receive()
        {
            EndPoint endPoint = new IPEndPoint(IPAddress.Any, 0); //用来保存发送方的ip和端口号
            var buffer = new byte[QQGlobal.QQPacketMaxSize];
            var len = _server.ReceiveFrom(buffer, ref endPoint);

            return new ReceiveData
            {
                Data = buffer,
                DataLength = len,
                From = endPoint
            };
        }`
卡到 _server.ReceiveFrom 这一句，在公司正常使用qq可以。请问这是什么原因？

**Comment by wzfxue** [comment]
@luojinfang 换了几个的确可以了，奇怪，一开始为了验证这个我还专门在qq设置上选择了sz6.tencent.com验证可以登录。

**Comment by luojinfang** [comment]
@wzfxue  后续试着添加一下自动切换

**Comment by wzfxue** [comment]
@luojinfang 那真是太棒了，这几个倒是都解析dns正常。如果自动切换的话得监控ReceiveFrom多久无响应之后重新换服务器登录吧

**Comment by wzfxue** [comment]
@luojinfang hello，建议增加对Receive监控，比如超过一段时间没有接收过消息则重新登录。昨天下午开着测试，晚上大概8点多就已经假死状态。
